source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DZAuthSession_Example', :exclusive => true do
  pod 'DZAuthSession', :path => '../'
end

target 'DZAuthSession_Tests', :exclusive => true do
  pod 'DZAuthSession', :path => '../'

  pod 'FBSnapshotTestCase'
end
